import { execSync } from "node:child_process";
import { readFileSync, appendFileSync, existsSync } from "node:fs";

import { diffManifests } from "./diff.js";
import { toMarkdown } from "./format.js";
import type { Manifest, BundleDiff } from "./types.js";

export interface RunnerEnv {
  inputs: Record<string, string | undefined>;
  GITHUB_OUTPUT?: string;
  GITHUB_EVENT_NAME?: string;
  GITHUB_REPOSITORY?: string;
  GITHUB_EVENT_PATH?: string;
  readFile?: (path: string) => string;
  exists?: (path: string) => boolean;
  gitShow?: (sha: string, path: string) => string | null;
  postComment?: (args: { token: string; repo: string; issueNumber: number; body: string }) => Promise<void>;
  write?: (line: string) => void;
}

export interface RunnerResult {
  exitCode: 0 | 1;
  diff: BundleDiff | null;
  newManifest: boolean;
  commentPosted: boolean;
  reason?: string;
}

const NULL_DIFF: BundleDiff = {
  changes: [],
  breaking: false,
  added: { items: [], relationships: [] },
  removed: { items: [], relationships: [] }
};

function defaultGitShow(sha: string, path: string): string | null {
  try {
    return execSync(`git show ${sha}:${path}`, { encoding: "utf8", stdio: ["ignore", "pipe", "ignore"] });
  } catch {
    return null;
  }
}

export async function run(env: RunnerEnv): Promise<RunnerResult> {
  const manifestPath = required(env.inputs, "manifest_path");
  const baseShaInput = env.inputs.base_sha ?? "";
  const commentOnPr = env.inputs.comment_on_pr ?? "auto";
  const failOnBreaking = (env.inputs.fail_on_breaking ?? "true").toLowerCase() !== "false";
  const failOnAnyChange = (env.inputs.fail_on_any_change ?? "false").toLowerCase() === "true";
  const token = env.inputs.github_token ?? "";

  const read = env.readFile ?? ((p) => readFileSync(p, "utf8"));
  const exists = env.exists ?? ((p) => existsSync(p));
  const gitShow = env.gitShow ?? defaultGitShow;
  const write = env.write ?? ((line) => process.stdout.write(`${line}\n`));

  if (!exists(manifestPath)) {
    write(`::error::manifest-path "${manifestPath}" does not exist on disk.`);
    return { exitCode: 1, diff: null, newManifest: false, commentPosted: false, reason: "manifest-path not found" };
  }

  let baseSha = baseShaInput;
  if (!baseSha && env.GITHUB_EVENT_PATH && exists(env.GITHUB_EVENT_PATH)) {
    try {
      const event = JSON.parse(read(env.GITHUB_EVENT_PATH)) as { pull_request?: { base?: { sha?: string } } };
      baseSha = event.pull_request?.base?.sha ?? "";
    } catch {
      // ignore
    }
  }

  let prev: Manifest | null = null;
  let prevRaw: string | null = null;
  if (baseSha) prevRaw = gitShow(baseSha, manifestPath);
  if (prevRaw !== null) {
    try {
      prev = JSON.parse(prevRaw) as Manifest;
    } catch (e) {
      write(`::warning::could not parse previous Manifest at ${baseSha}:${manifestPath} — treating as new manifest. (${(e as Error).message})`);
      prev = null;
    }
  }

  const nextRaw = read(manifestPath);
  const next = JSON.parse(nextRaw) as Manifest;

  const newManifest = prev === null;
  const diff = newManifest ? NULL_DIFF : diffManifests(prev as Manifest, next);
  const markdown = newManifest
    ? `_New evidence-bundle manifest at \`${manifestPath}\` — no previous version found at base SHA ${baseSha || "(no base SHA)"}._`
    : toMarkdown(diff);

  setOutput(env, "breaking", String(diff.breaking));
  setOutput(env, "change-count", String(diff.changes.length));
  setOutput(env, "new-manifest", String(newManifest));

  write(`\n${markdown}\n`);

  const isPullRequest = env.GITHUB_EVENT_NAME === "pull_request";
  const wantsComment = commentOnPr === "true" || (commentOnPr === "auto" && isPullRequest);
  let commentPosted = false;
  let reason: string | undefined;

  if (wantsComment) {
    if (!token) {
      reason = "no github-token provided";
    } else if (!env.GITHUB_EVENT_PATH) {
      reason = "no GITHUB_EVENT_PATH";
    } else if (!env.GITHUB_REPOSITORY) {
      reason = "no GITHUB_REPOSITORY";
    } else {
      const event = JSON.parse(read(env.GITHUB_EVENT_PATH)) as { number?: number; pull_request?: { number?: number } };
      const issueNumber = event.number ?? event.pull_request?.number;
      if (!issueNumber) {
        reason = "no PR number in event payload";
      } else {
        const body = `### Evidence Bundle diff — \`${manifestPath}\`\n\n${markdown}\n\n_Generated by [evidence-bundle-diff-action](https://github.com/mizcausevic-dev/evidence-bundle-diff-action)._`;
        const poster = env.postComment ?? defaultPostComment;
        await poster({ token, repo: env.GITHUB_REPOSITORY, issueNumber, body });
        commentPosted = true;
      }
    }
  }

  if (!newManifest && failOnBreaking && diff.breaking) {
    write(`::error::Evidence Bundle diff is BREAKING — ${diff.changes.length} change(s) detected.`);
    return { exitCode: 1, diff, newManifest, commentPosted, reason };
  }
  if (!newManifest && failOnAnyChange && diff.changes.length > 0) {
    write(`::error::Evidence Bundle manifest has ${diff.changes.length} change(s) and fail-on-any-change=true.`);
    return { exitCode: 1, diff, newManifest, commentPosted, reason };
  }

  return { exitCode: 0, diff, newManifest, commentPosted, reason };
}

function required(inputs: Record<string, string | undefined>, name: string): string {
  const v = inputs[name];
  if (!v || v.length === 0) throw new Error(`input "${name}" is required`);
  return v;
}

function setOutput(env: RunnerEnv, key: string, value: string): void {
  if (env.GITHUB_OUTPUT) appendFileSync(env.GITHUB_OUTPUT, `${key}=${value}\n`);
}

async function defaultPostComment(args: { token: string; repo: string; issueNumber: number; body: string }): Promise<void> {
  const r = await fetch(`https://api.github.com/repos/${args.repo}/issues/${args.issueNumber}/comments`, {
    method: "POST",
    headers: {
      Accept: "application/vnd.github+json",
      Authorization: `Bearer ${args.token}`,
      "X-GitHub-Api-Version": "2022-11-28"
    },
    body: JSON.stringify({ body: args.body })
  });
  if (!r.ok) throw new Error(`GitHub API comment failed: ${r.status} ${await r.text()}`);
}
